trigger:
    - main

pool: 
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- bash: echo hello world


- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'